<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 8" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="C:\Users\19augusthummert\Google Drive\Code\Chapter5\CircleOfShapes.py" status="error" test="CircleOfShapes" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\19augusthummert\.p2\pool\plugins\org.python.pydev_5.4.0.201611281236\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:/Users/19augusthummert/Google Drive/Code/Chapter5\CircleOfShapes.py", line 43, in <module>
    sys.exit()
SystemExit
ERROR: Module: CircleOfShapes could not be imported (file: C:\Users\19augusthummert\Google Drive\Code\Chapter5\CircleOfShapes.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Chapter5 CircleOfShapes.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
